### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by sampullman** [samatechtw/vue-store#1]
Add unit tests with Jest. This should be done once the Store/Module API is in a stable state.

- [x] Add jest package and config
- [x] Add tests directory and package.json script
- [x] Add tests covering basic usage

**Comment by sampullman** [comment]
Usually I only do "rebase merging" from Github, but this one isn't a problem. I just changed the settings for future use, only rebase is enabled now.

**Comment by abemscac** [comment]
So did I break anything?
Is everything okay?
I'm so sorry.

**Comment by sampullman** [comment]
No problem at all! It's just an aesthetic preference, I like to keep the history linear.
