### ISSUE TITLE
Github actions CI

### ISSUE THREAD

**Issue by sampullman** [samatechtw/vue-store#2]
Add some CI checks with Github actions

- [ ] Prettier format
- [ ] ESLint lint
- [ ] Build
- [ ] Test

**Comment by sampullman** [comment]
@abemscac Here is a reference to some checks that are almost identical to what we need: [pr-commit](https://github.com/samatechtw/onflow-ts/blob/main/.github/workflows/pr-commit.yml)

There's also a [publish](https://github.com/samatechtw/onflow-ts/blob/main/.github/workflows/publish.yml) script we could use to help automate NPM package publishing, but that's not necessary to cover in this issue.

**Comment by abemscac** [comment]
No problem, I'll take a look in a few days.
Thank you Sam.
