### ISSUE TITLE
Decouple local storage to plugin

### ISSUE THREAD

**Issue by sampullman** [samatechtw/vue-store#4]
Currently, the Store always saves to localstorage on change. By default, it should be a memory store, and we should provide a plugin for saving to localstorage. The benefits are:

- Many apps need both memory storage and persisted storage. This allows using the same Store/Module interface for both cases.
- Some apps may prefer to persist the Store using a different storage method
- The plugin architecture may be re-used for other purposes (custom serializability, etc)

The plugin system should have the following properties:
- [ ] Initialization callback for setting up the state. The input is the the initial state (undefined for the first plugin), and the output is an object. The last plugin to run must produce an object that is a valid Store state.
- [ ] Change callback triggered via `watch`. It should transparently pass the parameters provided by watch to the plugin
- [ ] Plugins run in order, and can transform the result of the previous plugin

**Comment by abemscac** [comment]
Hi @sampullman.

About the plugin system, I wonder which way is more practical/convenient/easy-to-use for developers.

- Global config
  Just like the `Plugin` for Vue, these plugins will effect every module (or root-module only) initialized by VueStore.
  ```ts
  import VueStore from 'vue-store'
  
  VueStore.use(PluginA, PluginB, PluginC...)
  ```

- Per module config
  ```ts
  const userModule = new Module({
    name: 'web',
    version: 1,
    stateInit: () => ({
      id: 0,
      name: '',
    }),
    plugins: [PluginA, PluginB, PluginC...],
  })
  ```
  
Also, do plugins run before, or after the module initialization is done? It feels like it's before, because I guess plugin is a way to mutate the options used to initialize the module.
Am I misunderstanding anything?

**Comment by abemscac** [comment]
So can we say that:
- `state` is the only property a plugin can mutate
- `stateInit` will no longer be a required property because we have `onStateInit` hook in plugins.
- plugins are like pipes

For example:

```ts
const userModule = new Module({
  name: 'web',
  version: 1,
  stateInit: () => ({
    id: 0,
    name: '',
  }),
  plugins: [
    // For PluginA, the "state" argument in "onStateInit" will be { id: 0, name: '' } because the source stateInit function returns it, but could possibly be undefined
    PluginA,
    // For PluginB, the "state" argument in "onStateInit" will be whatever is returned from the "onStateInit" of PluginA,
    // because PluginA is the preceeding plugin of PluginB
    PluginB,
  ],
})
```

**Comment by sampullman** [comment]
> state is the only property a plugin can mutate

I think so, but something else will become obvious once we try implementing it. For example, maybe there will eventually be a use case for passing in the "current" transformed state (e.g. the latest result in the pipe), as well as the original unmodified state? Probably not worth worrying too much about at first.

> stateInit will no longer be a required property because we have onStateInit hook in plugins

I'm not sure about this one, I think it's still useful to require a `stateInit` so that it's obvious what the original state of the data is.

> plugins are like pipes

Yep!

To avoid the problem you're mentioning, I think we should restrict the output state to be the same type as the input state. I think it will still be flexible enough to handle most situations, and will save us a lot of trouble.

If a developer wanted to include an extra field in the output of a Plugin, they could add the field as `thing: string | undefined`. Maybe a little messy, but I think it's better than losing type checks on the whole store.

**Comment by abemscac** [comment]
Great!
I think I get it now, thank you!
